### ISSUE TITLE
Feedback/komplettering

### ISSUE THREAD

**Issue by simonlindholm** [inda18plusplus/ggerholm-crypto#2]
I marked the important points with (!), the rest you can do as you want with. Hopefully they are useful feedback!

- I see you added authentication to ensure that only client and server can communicate, and encryption to ensure that eavesdroppers can't determine which files are changed. Nice! Some feedback related to this:
  * Using a shared secret for auth is a fine idea. Why two secrets, though?
  * (!) Keys are send in plain text (note that signing does not encrypt), and there is no guarantee that the signing keys get sent over correctly; a MITM could be in the way. So the authentication doesn't really work.
  * Since you have a shared secret key, there's no reason to use asymmetric (public key) cryptography. For authentication with symmetric crypto you could use e.g. https://pynacl.readthedocs.io/en/stable/hashing/#message-authentication, and for encryption `SecretBox`. I guess you *could* throw in some public key crypto if you want perfect forward secrecy (e.g. by generating an ephemeral keypair to transmit randomness), but you can do that on top of the symmetric encryption.
  * The default_ssl=True code looks solid.

- `if server_secret != self.server_secret` -- fun fact, you can perform a (difficult) timing attack against this. A server can guess secrets at random, send them to the client, and measure how long it takes the client to reject them. Hard, since the difference is on the order of nanoseconds, but still a problem if an attacker can make a couple of billion attempts and has good network conditions. NaCl has functions for constant time string comparison, but it looks like PyNaCl doesn't expose them. Anyway, this will go away when you fix the above.

- I note that reads and writes both take linear time to perform on the server, e.g. for recomputing the tree and searching for file objects. That's fine, but note that it can be done in O(log N) time with some cleverness.

- I found it very hard to review the Merkle tree verification:
  * the server is allowed to pass back an arbitrary partial tree, which could have many possible forms. If it was more constrained (only e.g. a list of hashes down the tree) it would have been easier to review that all necessary checks are done in all cases.
  * the client takes this data and creates a tree with a mix of trusted and untrusted data. This makes it hard to know that the right checks are done in all circumstances and that the client doesn't accidentally trust data it shouldn't.

It would be much better to have a simple recursive algorithm, that only uses the list of hashes down the tree and nothing else. This is hard to do anything about without a large rewrite, and I can't say for sure whether it's incorrect, so I'll let it slide, but it's worth keeping in mind for the future that reviewability, simple code and clear trust barriers are important for security.

- On the same subject, but simpler to fix, `_json_object_hook` should validate types. (Again this falls within the umbrella of trusting data too much.)

- (!) There is no verification that the file received is the one at the requested index.

- (!) At writes, there is no verification that the hashes returned match the old root hash. So at writes the server can change the files arbitrarily (swap them around, replace them with old versions, etc.).

Also, a couple of minor code comments:
- I appreciate the type annotations that exist. :) (More would be even better. mypy is great.)
- `if len(encrypted) != len(data) + secret_box.NONCE_SIZE + secret_box.MACBYTES` -- can this really happen? (i.e. can encrypt fail?) otherwise, make it an assert.
- Exceptions are probably better than `None` return values -- they are harder to accidentally ignore, and more Pythonic

**Comment by Sourc** [comment]
There are two secrets because when I first began my goal was to implement something more like SSL certificates and not have any shared secrets. When I scrapped that idea I just kept the files I had used as is instead of combining them.

Because I tried to keep the server and client completly independet of each other (no shared files) I had some issues when I researched the ways to share the secret/symmetric key that was generated at runtime. I decided upon using public/private keys for the initial exchange but clearly had some gaps in my knowledge when I implemented it. I'll have to get around to fixing that at some point. In the meantime I swapped to the default SSL impementation (I made it for a reason).

I did have an unnecessary for loop within the update method of the merkle tree (though it did not make it O(n)) but other than that I don't see how the merkle tree calculation is O(n). I did save the files on the server in a list of no specific order which required a loop to find the correct file. I assume that's what you meant was O(n) for both writing and finding files on the server?

I've not resolved the issue that the new root hash sent over by the sever is not verified in anyway. Seeing as the client does not have a complete merkle tree of it's own to compare with and the previous trees sent over by the server are only partial so a comparison is not simply == my initial thought was that I would have to think about this issue a little more, which I don't feel like now.

The `if len(encrypted)...` was something I saw used in PyNaCl examples and simply included here aswell.
I agree that exceptions would be better. I was lazy and decided to return False / None because exception-handling requires at least two more lines of code to handle.

**Comment by simonlindholm** [comment]
> (no shared files)

You do need some initially shared files, or else you can't distinguish the party you want to communicate with from a MITM. You could use non-secrets, though, e.g. generating a keypair with `PrivateKey.generate()`/`SigningKey.generate()` and storing the other party's public half.

> In the meantime I swapped to the default SSL impementation (I made it for a reason).

Sounds good!

> I did have an unnecessary for loop within the update method of the merkle tree (though it did not make it O(n)) but other than that I don't see how the merkle tree calculation is O(n). I did save the files on the server in a list of no specific order which required a loop to find the correct file. I assume that's what you meant was O(n) for both writing and finding files on the server?

`get_structure_with_file` does lot of `deepcopy`s, aren't those O(n)?

> my initial thought was that I would have to think about this issue a little more, which I don't feel like now.

Take your time, crypto is not to be hurried. :) it shouldn't be too hard, though, I think.

> The if len(encrypted)... was something I saw used in PyNaCl examples and simply included here aswell.

I saw https://pynacl.readthedocs.io/en/stable/secret/#example do the same thing in an assert, and in that form it makes more sense (it's more like a comment, but with some added verification).

> exception-handling requires at least two more lines of code to handle.

depends on where you put the try-excepts, I guess

**Comment by simonlindholm** [comment]
Wait, another thing. The client never encrypts the data it stores on the server, the only encryption done is when the data is in transit. Can you make the client encrypt the data it stores using some password/persistent key?

**Comment by Sourc** [comment]
You're correct about the deepcopies. I forgot I had those, that's resolved now. Did the assignment say that the data should only be readable by the client? I'll have to read it more thoroughly next time then. I assumed that anyone on the server should be able to see the contents of the files, which is why I implemented the whole project this way (instead of keeping all encryption/decryption on the client).

**Comment by simonlindholm** [comment]
It did, and even with multiple clients it would be good to prevent the server from eavesdropping. (Also, note that the "store root hash at the client" scheme doesn't make much sense with multiple clients, as described in the third "possible extension" section of the homework.) Anyway, should be a simple change to add that encryption.

**Comment by Sourc** [comment]
I've now implemented further data encryption, stored public/private keys and I believe a working check against malicious server modifications to the files. I suppose the secret key could be saved right away in a file instead of going through all the trouble of using public/private keys to setup a completely new one each time (like I believe you suggested in the first comment) but whatever.

**Comment by simonlindholm** [comment]
Finally got around to looking at the changes (sorry for the extreme delay; at least I didn't interrupt any compiler work...).

The protection against malicious server modifications doesn't work -- the server could lie during both `send_file` and `get_structure`. You need to use the old locally stored top hash somehow, that's the only means you have of authenticating things.

Also, a minor point. The client encrypts files using a random key, unique per session, which means that when you restart it you cannot recover your files any more. Could you change the key to be password-based (like the homework says :))?

**Comment by Sourc** [comment]
I've added an if-statement for that. I suppose I could skip the seperate `get_structure` too, tho I haven't made that change for now. I've also added the user-provided password thing.

**Comment by simonlindholm** [comment]
Looks great!
